version: '2'
services:
  zookeeper-src-a:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-src-b:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

